version: '3.9'

services:
  # App
  bdk-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - bdk-mysql
      - bdk-redis
      - bdk-nginx
    image: bdk-service
    container_name: bdk-service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: bdk-service
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # Web Server
  bdk-nginx:
    image: nginx:alpine
    container_name: bkd-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "1080:80"
      - "10443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  # Database
  bdk-mysql:
    image: mysql
    container_name: bdk-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "10306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gL1hE2tA2bA1cL1m
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: aC0qD1nA0eQ2aB3e
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    volumes:
      - ./docker/data/:/var/lib/mysql/
      - ./docker/mysql/conf/:/etc/mysql/
      - ./docker/mysql/files/:/var/lib/mysql-files/
  bdk-redis:
    image: redis
    container_name: bdk-redis
    restart: unless-stopped
    ports:
      - "10379:6379"
    volumes:
      - ./docker/redis/data:/data
      - ./docker/redis/redis.conf:/etc/redis.conf
